-- Enable Row Level Security
alter table if exists public.site_settings enable row level security;
alter table if exists public.portfolio enable row level security;

-- Create site_settings table
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  company_name text not null default 'Jumba Glass & Aluminium',
  logo_url text,
  owner_name text default 'John Doe',
  owner_role text default 'Founder',
  owner_bio text,
  owner_image_url text,
  primary_color text default '#0f172a',
  phone_primary text,
  email_primary text,
  address text
);

-- Create portfolio table
create table if not exists public.portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Policies for site_settings
drop policy if exists "Allow public read access" on public.site_settings;
create policy "Allow public read access"
  on public.site_settings for select
  using (true);

drop policy if exists "Allow authenticated update access" on public.site_settings;
create policy "Allow authenticated update access"
  on public.site_settings for update
  using (auth.role() = 'authenticated');

-- Policies for portfolio
drop policy if exists "Allow public read access" on public.portfolio;
create policy "Allow public read access"
  on public.portfolio for select
  using (true);

drop policy if exists "Allow authenticated insert access" on public.portfolio;
create policy "Allow authenticated insert access"
  on public.portfolio for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Allow authenticated update access" on public.portfolio;
create policy "Allow authenticated update access"
  on public.portfolio for update
  using (auth.role() = 'authenticated');

drop policy if exists "Allow authenticated delete access" on public.portfolio;
create policy "Allow authenticated delete access"
  on public.portfolio for delete
  using (auth.role() = 'authenticated');

-- STORAGE CONFIGURATION
-- Create storage bucket for images (jumba-assets)
insert into storage.buckets (id, name, public) 
values ('jumba-assets', 'jumba-assets', true)
on conflict (id) do nothing;

-- Storage Policies
-- 1. Public Read Access
drop policy if exists "Allow public read access to jumba-assets bucket" on storage.objects;
create policy "Allow public read access to jumba-assets bucket"
  on storage.objects for select
  using ( bucket_id = 'jumba-assets' );

-- 2. Authenticated Upload Access
drop policy if exists "Allow authenticated upload access to jumba-assets bucket" on storage.objects;
create policy "Allow authenticated upload access to jumba-assets bucket"
  on storage.objects for insert
  with check ( bucket_id = 'jumba-assets' and auth.role() = 'authenticated' );

-- 3. Authenticated Update Access
drop policy if exists "Allow authenticated update access to jumba-assets bucket" on storage.objects;
create policy "Allow authenticated update access to jumba-assets bucket"
  on storage.objects for update
  using ( bucket_id = 'jumba-assets' and auth.role() = 'authenticated' );

-- 4. Authenticated Delete Access
drop policy if exists "Allow authenticated delete access to jumba-assets bucket" on storage.objects;
create policy "Allow authenticated delete access to jumba-assets bucket"
  on storage.objects for delete
  using ( bucket_id = 'jumba-assets' and auth.role() = 'authenticated' );

-- Seed initial data for site_settings
insert into public.site_settings (id, company_name, phone_primary, email_primary, address)
values (1, 'Jumba Glass & Aluminium', '+254 700 000000', 'info@jumbaglass.com', 'Nairobi, Kenya')
on conflict (id) do nothing;
